[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 8, unit = " " }
# auto-format = true
# formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "make"
file-types = ["Makefile", "in", "make"]

[[language]]
name = "rust"
auto-format = true
language-server = { command = "rust-analyzer" } #, args = ["--target-dir", "/tmp/rust-analyzer-check"] }
[language.config.checkOnSave]
command = "clippy"
extraArgs = ["--", "-W", "clippy::pedantic"]

[[language]]
name = "bash"
# auto-format = true
file-types = [ "sh", { suffix = "pre-commit"}]
