theme = "slick"
icons = "awesome"

[[block]]
block = "battery"
driver = "sysfs"
device = "BAT0"
interval = 10
format = "{percentage} {time}"
full_format = "{percentage} {time}"

[[block]]
block = "backlight"
# [block.theme_overrides]
# idle_bg = "#931db4"

[[block]]
block = "sound"
step_width = 2
# [block.theme_overrides]
# idle_bg = "#931db4"

[[block]]
block = "disk_space"
path = "/home/"
alias = "/home/"
info_type = "available"
unit = "GB"
interval = 10
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
display_type = "memory"
icons = true
clickable = false
interval = 1
warning_mem = 80
critical_mem = 90
[block.theme_overrides]
# idle_bg = "#2196f3"
# idle_fg = "#000000"
idle_bg = "#8bc34a"
idle_fg = "#000000"

[[block]]
block = "cpu"
interval = 1
# [block.theme_overrides]
# idle_bg = "#8bc34a"
# idle_fg = "#000000"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_include = ["wlp2s0", "enp0s20f0u4u4"]

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R"
