[theme]
theme = "slick"

[icons]
icons = "awesome6"

[[block]]
block = "battery"
# device = "BAT0"
# format = " $icon $percentage $time"
# full_format = "$icon $percentage $time"
format = " $icon $percentage $time / $power "
full_format = " $icon $percentage "
[block.theme_overrides]
idle_bg = { link = "good_bg" }
idle_fg = { link = "good_fg" }
good_bg = "#8bc34a"
good_fg = "#000000"

[[block]]
block = "backlight"
# [block.theme_overrides]
# idle_bg = "#931db4"

[[block]]
block = "sound"
step_width = 2
[block.theme_overrides]
idle_bg = "#8bc34a"
idle_fg = "#000000"

[[block]]
block = "disk_space"
path = "/home/"
# alias = "/home/"
info_type = "available"
alert_unit = "GB"
interval = 10
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
format = "$mem_used/$mem_total($mem_used_percents)"
# display_type = "memory"
# icons = true
# clickable = false
interval = 1
warning_mem = 80
critical_mem = 90
[block.theme_overrides]
# idle_bg = "#2196f3"
# idle_fg = "#000000"
idle_bg = "#8bc34a"
idle_fg = "#000000"

[[block]]
block = "cpu"
interval = 1
# [block.theme_overrides]
# idle_bg = "#8bc34a"
# idle_fg = "#000000"

[[block]]
block = "bluetooth"
mac = "08:EB:ED:CE:FD:D1"
disconnected_format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "bluetooth"
mac = "DC:2C:26:38:53:54"
disconnected_format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|} $ip "
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%a %d/%m %R')"
